GOOGLE_CLIENT_ID = "1084663495412-ast0nrgoqklvlu41dvhhsf9b8u2kaqdj.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "http://localhost:8501/"
 
MONGO_URI_HOST = "mongodb+srv://" 
MONGO_URI_SERVER = "@lfscluster.b3u9d.mongodb.net/?retryWrites=true&w=majority&appName=lfsCluster"
MONGO_USER = "willteey:"
MONGO_PASSWORD = "UcheIfyEsther@2024"
MONGO_DB_NAME = "lfsCluster"