GOOGLE_CLIENT_ID = "1084663495412-ast0nrgoqklvlu41dvhhsf9b8u2kaqdj.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "http://localhost:8501/"

MONGO_URI = "your_mongo_db_uri"
MONGO_DB_NAME = "your_database_name"